export const lightTheme = {
  name: 'light',
  colors: {
    background: '#fff',
    textPrimary: '#000',
    textHighlight: '#a18a68',
    textLight: '#707070',
    inactiveDot: '#fff',
    activeDot: 'transparent',
    cardBackground: 'rgba(255, 255, 255, 0.5);',
    border: '#d8d8d8',
    footerLink: '#707070',
    burger: '#000',
    icon: 'transparent',
    button: '#000',
    buttonText: '#fff',
  },
}
export const darkTheme = {
  name: 'dark',
  colors: {
    background: '#1a1a1a',
    textPrimary: '#fff',
    textHighlight: '#a18a68',
    textLight: '#707070',
    inactiveDot: '#333',
    activeDot: '#fff',
    cardBackground: 'rgba(26, 26, 26, 0.5)',
    border: '#333',
    footerLink: '#b3b3b3',
    burger: '#fff',
    icon: '#fff',
    button: '#fff',
    buttonText: '#000',
  },
}
